eunchong_test_FullRequest
osamhack2021/APP_ConveUntact_Yookhaehan pull request #4
Opened 2021-09-18 09:07 UTC by dmsvk01

test입니다

2021-09-18 23:26 UTC, zhoho requested changes
test

2021-09-18 23:26 UTC, zhoho commented on myapp/lib/main.dart
What is it?

2021-09-18 23:26 UTC, zhoho commented
good job bro

2021-09-19 07:23 UTC, dmsvk01 commented on myapp/lib/main.dart
.

2021-09-20 01:01 UTC, closed without merging